"""create_restaurant_table

Revision ID: 088070ab8e4c
Revises: 2d7a122257e8
Create Date: 2025-05-29 12:43:18.474507

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '088070ab8e4c'
down_revision = '2d7a122257e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('restaurant', sa.Column('revo_tenant', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('restaurant', sa.Column('revo_client_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('restaurant', sa.Column('revo_api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('restaurant', 'description')
    op.drop_column('restaurant', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('restaurant', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('restaurant', 'revo_api_key')
    op.drop_column('restaurant', 'revo_client_key')
    op.drop_column('restaurant', 'revo_tenant')
    op.drop_column('restaurant', 'name')
    # ### end Alembic commands ###
