"""create_restaurant_table

Revision ID: 2d7a122257e8
Revises: 7d1ba9b6fdf4
Create Date: 2025-05-29 12:23:45.855318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d7a122257e8'
down_revision = '7d1ba9b6fdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
