"""create_restaurant_table

Revision ID: a60df6e28f49
Revises: 088070ab8e4c
Create Date: 2025-05-29 12:50:05.872528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a60df6e28f49'
down_revision = '088070ab8e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
